---
- name: download
  get_url:
    url: "{{ velero_url }}"
    dest: /tmp
    checksum: "{{ velero_checksum }}"

- name: Check Ansible version
  command: ansible --version
  register: ansibleVersion

- name: Print version
  debug:
    msg: "Ansible Version: {{ ansibleVersion.stdout }}"

- name: Check tmp content
  command: ls /tmp
  register: tmpContent

- name: Print tmp content
  debug:
    msg: "tmp content: {{ tmpContent.stdout }}"

- block:
    - name: unarchive
      unarchive:
        src: "/tmp/{{ velero_pkg_ext }}"
        dest: /tmp
        remote_src: true
        creates: "{{ velero_bin }}"

    - name: executable bin for every user
      copy:
        src: "/tmp/{{ velero_pkg_bin }}"
        dest: "{{ velero_bin }}"
        owner: root
        group: root
        mode: '0755'
  become: true
