---
- name: download
  get_url:
    url: "{{ velero_url }}"
    dest: /tmp
    checksum: "{{ velero_checksum }}"

- block:
    - name: unarchive
      unarchive:
        src: "{{ velero_download_bin }}"
        dest: /tmp
        remote_src: true
        creates: "{{ velero_bin }}"

    - name: executable bin for every user
      copy:
        src: "{{ velero_downloaded_bin }}"
        dest: "{{ velero_bin }}"
        owner: root
        group: root
        mode: '0755'
  become: true
